#define uint2 uvec2
#define float4 vec4
#define uint4 uvec4


struct CurveData
{
  vec4 xybc;
  vec4 d;
};

struct Coord
{
  uvec4 x;
  uvec4 y;
};

struct Coordf
{
  vec4 x;
  vec4 y;
};

struct EnvParams
{
    uvec2 tile;
  uvec2 textureOffset; // if we are writing to a texture

  // Current tile offset
  uvec2 tileOffset;
  // Current tile size
  uvec2 tileSize;
  // Offset within the tile
  uvec2 offset;
  // Size within the tile
  uvec2 size; // writable size
  // Derived : Reciprocal size
  vec2 recipSize;
  // Derived : Reciprocal tileSize
  vec2 recipTileSize;

  float    frequency;
  float    wavelength;
  uint seed;
  uint bufferArraySize;
};


const ivec4   FnPrimes_X = ivec4( 501125321 );
const ivec4   FnPrimes_Y = ivec4( 1136930381 );
const vec4 ROOT2      = vec4( 1.4142135623730950488 );
const vec4 ROOT3      = vec4( 1.7320508075688772935 );
const vec4 SQRT3      = vec4( 1.7320508075688772935274463415059 );
const vec4 F2         = vec4( vec4( 0.5 ) * ( SQRT3 - vec4( 1.0 ) ) );
const vec4 G2         = vec4( ( vec4( 3.0 ) - SQRT3 ) / vec4( 6.0 ) );

