
vec4 ltsel( vec4 a, vec4 b, vec4 v1, vec4 v2 )
{
    return vec4( a.x < b.x ? v1.x : v2.x, a.y < b.y ? v1.y : v2.y, a.z < b.z ? v1.z : v2.z, a.w < b.w ? v1.w : v2.w );
}

vec4 gtsel( vec4 a, vec4 b, vec4 v1, vec4 v2 )
{
    return vec4( a.x > b.x ? v1.x : v2.x, a.y > b.y ? v1.y : v2.y, a.z > b.z ? v1.z : v2.z, a.w > b.w ? v1.w : v2.w );
}

ivec4 less_than( vec4 a, vec4 b )
{
    return ivec4( a.x < b.x, a.y < b.y, a.z < b.z, a.w < b.w );
}

ivec4 greater_than( vec4 a, vec4 b )
{
    return ivec4( a.x > b.x, a.y > b.y, a.z > b.z, a.w > b.w );
}

vec4 select( ivec4 mask, vec4 a, vec4 b )
{
    return vec4( mask.x != 0 ? a.x : b.x, mask.y != 0 ? a.y : b.y, mask.z != 0 ? a.z : b.z, mask.w != 0 ? a.w : b.w );
}

// -- MASKED MUL --
ivec4 mask_mul( ivec4 a, ivec4 b, ivec4 mask )
{
    return ivec4( mask.x != 0 ? a.x * b.x : a.x, mask.y != 0 ? a.y * b.y : a.y, mask.z != 0 ? a.z * b.z : a.z,
                   mask.w != 0 ? a.w * b.w : a.w );
}

vec4 mask_mul( vec4 a, vec4 b, ivec4 mask )
{
    return vec4( mask.x != 0 ? a.x * b.x : a.x, mask.y != 0 ? a.y * b.y : a.y, mask.z != 0 ? a.z * b.z : a.z,
                   mask.w != 0 ? a.w * b.w : a.w );
}

// -- MASKED ADD --
ivec4 mask_add( ivec4 a, ivec4 b, ivec4 mask )
{
    return ivec4( mask.x != 0 ? a.x + b.x : a.x, mask.y != 0 ? a.y + b.y : a.y, mask.z != 0 ? a.z + b.z : a.z,
                 mask.w != 0 ? a.w + b.w : a.w );
}

vec4 mask_add( vec4 a, vec4 b, ivec4 mask )
{
    return vec4( mask.x != 0 ? a.x + b.x : a.x, mask.y != 0 ? a.y + b.y : a.y, mask.z != 0 ? a.z + b.z : a.z,
                 mask.w != 0 ? a.w + b.w : a.w );
}

ivec4 nmask_add( ivec4 a, ivec4 b, ivec4 mask )
{
    return ivec4( mask.x != 0 ? a.x : a.x + b.x, mask.y != 0 ? a.y : a.y + b.y, mask.z != 0 ? a.z : a.z + b.z,
                 mask.w != 0 ? a.w : a.w + b.w );
}

vec4 nmask_add( vec4 a, vec4 b, ivec4 mask )
{
    return vec4( mask.x != 0 ? a.x : a.x + b.x, mask.y != 0 ? a.y : a.y + b.y, mask.z != 0 ? a.z : a.z + b.z,
                 mask.w != 0 ? a.w : a.w + b.w );
}

// -- MASKED SUB --
ivec4 mask_sub( ivec4 a, ivec4 b, ivec4 mask )
{
    return ivec4( mask.x != 0 ? a.x - b.x : a.x, mask.y != 0 ? a.y - b.y : a.y, mask.z != 0 ? a.z - b.z : a.z,
                 mask.w != 0 ? a.w - b.w : a.w );
}

vec4 mask_sub( vec4 a, vec4 b, ivec4 mask )
{
    return vec4( mask.x != 0 ? a.x - b.x : a.x, mask.y != 0 ? a.y - b.y : a.y, mask.z != 0 ? a.z - b.z : a.z,
                 mask.w != 0 ? a.w - b.w : a.w );
}

ivec4 nmask_sub( ivec4 a, ivec4 b, ivec4 mask )
{
    return ivec4( mask.x != 0 ? a.x : a.x - b.x, mask.y != 0 ? a.y : a.y - b.y, mask.z != 0 ? a.z : a.z - b.z,
                 mask.w != 0 ? a.w : a.w - b.w );
}

vec4 nmask_sub( vec4 a, vec4 b, ivec4 mask )
{
    return vec4( mask.x != 0 ? a.x : a.x - b.x, mask.y != 0 ? a.y : a.y - b.y, mask.z != 0 ? a.z : a.z - b.z,
                 mask.w != 0 ? a.w : a.w - b.w );
}

ivec4 nequal( ivec4 a, ivec4 b )
{
    return ivec4( a.x != b.x, a.y != b.y, a.z != b.z, a.w != b.w );
}

ivec4 hash_primes( ivec4 seed, ivec4 x, ivec4 y )
{
    ivec4 hash = seed;
    hash ^= x ^ y;
    hash *= ivec4( 0x27d4eb2d );
    return ( hash >> ivec4( 15 ) ) ^ hash;
}


vec4 gradient_dot( ivec4 hash, vec4 x, vec4 y )
{
    ivec4 bit1 = hash << ivec4( 31 );
    ivec4 bit2 = ( hash >> ivec4( 1 ) ) << 31;
    ivec4 mask = nequal( ivec4( hash & ivec4( 1 << 2 ) ), ivec4( 0 ) );
    x         = intBitsToFloat( floatBitsToInt( x ) ^ floatBitsToInt( bit1 ) );
    y         = intBitsToFloat( floatBitsToInt( y ) ^ floatBitsToInt( bit2 ) );
    vec4 a  = select( mask, y, x );
    vec4 b  = select( mask, x, y );
    return ( vec4( 1.0f ) + ROOT2 ) * a + b;
}

vec4 nmask( vec4 a, ivec4 m )
{
    return select( m, vec4( 0.0 ), a );
}

vec4 gradient_dot_fancy( ivec4 hash, vec4 x, vec4 y )
{
    ivec4 index = ivec4( vec4( hash & ivec4( 0x3FFFFF ) ) * vec4( 1.3333333333333333f ) );

    ivec4   xy  = index << 29;
    vec4 a   = select( xy, y, x );
    vec4 b   = select( xy, x, y );
    b          = intBitsToFloat( floatBitsToInt( b ) ^ ( index << 31 ) );
    ivec4 amul2 = ( index << 30 ) >> 31;
    a *= select( amul2, vec4( 2.0 ), ROOT3 );
    b = nmask( b, amul2 );

    // Bit-8 = Flip sign of a + b
    return intBitsToFloat( floatBitsToInt( a + b ) ^ ( ( index >> 3 ) << 31 ) );
}


bool is_within_tile(uint x, uint y, uint2 min_tile_vtx, uint2 max_tile_vtx)
{
  return (x >= min_tile_vtx.x && x < max_tile_vtx.x) && (y >= min_tile_vtx.y && y < max_tile_vtx.y); 
}

Coord get_offset(NodeParams params)
{
  Coord c;
  uint width = uint(params.env.size.x + 2);
  uvec4 slots = uvec4(gl_GlobalInvocationID.x * 4) + uvec4(0, 1, 2, 3);
  c.x = slots % width;
  c.y = slots / width;
  return c;
}

Coord apply_start_offset(Coord c, NodeParams params)
{
  c.x += uvec4(params.env.start_coord.x);
  c.y += uvec4(params.env.start_coord.y);
  return c;
}

Coord get_coord(NodeParams params)
{
  return apply_start_offset( get_offset(params), params );
}

Coordf get_coord_scaled(NodeParams params)
{
  Coord c = apply_start_offset( get_offset(params), params );
  Coordf rc;
  rc.x = vec4(c.x) * vec4(params.env.frequency);
  rc.x = vec4(c.y) * vec4(params.env.frequency);
  return rc;
}

uvec4 get_pixel_id(uvec4 x, uvec4 y, NodeParams params)
{
  uvec4 ux = uvec4(uvec4(x) - uvec4(params.env.start_coord.x));
  uvec4 uy = uvec4(uvec4(y) - uvec4(params.env.start_coord.y)) * uvec4(params.env.size.x + 2);
  return ux + uy;
}

uint get_pixel_id(uint x, uint y, NodeParams params)
{
  uint ux = (uint(x) - uint(params.env.start_coord.x));
  uint uy = (uint(y) - uint(params.env.start_coord.y)) * (params.env.size.x + 2);
  return ux + uy;
}
