
vec4 simplex( vec4 x, vec4 y, int3 pixel, env_params params )
{
    vec4 f  = vec4( F2 ) * ( x + y );
    vec4 x0 = floor( x + f );
    vec4 y0 = floor( y + f );

    ivec4 i = ivec4( x0 ) * FnPrimes_X;
    ivec4 j = ivec4( y0 ) * FnPrimes_Y;

    vec4 g = vec4( G2 ) * ( x0 + y0 );
    x0       = x - ( x0 - g );
    y0       = y - ( y0 - g );
    ivec4 i1  = greater_than( x0, y0 );

    vec4 x1 = mask_sub( x0, vec4( 1.0 ), i1 ) + G2;
    vec4 y1 = mask_sub( y0, vec4( 1.0 ), i1 ) + G2;

    vec4 x2 = x0 + vec4( G2 * 2 - 1 );
    vec4 y2 = y0 + vec4( G2 * 2 - 1 );

    vec4 t0 = max( ( vec4( 0.5 ) - ( y0 * y0 ) ) - ( x0 * x0 ), vec4( 0 ) );
    vec4 t1 = max( ( vec4( 0.5 ) - ( y1 * y1 ) ) - ( x1 * x1 ), vec4( 0 ) );
    vec4 t2 = max( ( vec4( 0.5 ) - ( y2 * y2 ) ) - ( x2 * x2 ), vec4( 0 ) );

    t0 *= t0;
    t0 *= t0;
    t1 *= t1;
    t1 *= t1;
    t2 *= t2;
    t2 *= t2;

    ivec4   seed = ivec4( params.seed );
    vec4 n0   = gradient_dot( hash_primes( seed, i, j ), x0, y0 );
    vec4 n1 =
        gradient_dot( hash_primes( seed, mask_add( i, FnPrimes_X, i1 ), nmask_add( j, FnPrimes_Y, i1 ) ), x1, y1 );
    vec4 n2 = gradient_dot( hash_primes( seed, i + ivec4( FnPrimes_X ), j + ivec4( FnPrimes_Y ) ), x2, y2 );

    return vec4( 38.283687591552734375f ) * ( n0 * t0 + ( n1 * t1 + n2 * t2 ) );
}
